function(hellogpu_init_target targetName)
	set_target_properties(${targetName}
	PROPERTIES
		CXX_STANDARD 23
		CXX_SCAN_FOR_MODULES YES)

	target_compile_options(${targetName} PRIVATE
		$<$<CXX_COMPILER_ID:MSVC>:/W4 /WX>
		$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall -Wextra -Wpedantic -Werror>
	)

	target_compile_definitions(${targetName} PRIVATE
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_PLATFORM}>,WINDOWS>:
			WIN32_LEAN_AND_MEAN
			NOMINMAX
			HELLOGPU_PLATFORM_WINDOWS
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_PLATFORM_ARCH}>,X64>:
			HELLOGPU_ARCH_X64
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_COMPILER}>,CLANG>:
			HELLOGPU_COMPILER_CLANG
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_COMPILER}>,MSVC>:
			HELLOGPU_COMPILER_MSVC
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_BUILD_CONFIG}>,DEBUG>:
			HELLOGPU_DEBUG
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_BUILD_CONFIG}>,DEVELOPMENT>:
			HELLOGPU_DEVELOPMENT
		>
		$<$<STREQUAL:$<UPPER_CASE:${HELLOGPU_BUILD_CONFIG}>,RELEASE>:
			HELLOGPU_RELEASE
		>
	)
endfunction()